name: Generate Android Compose App

on:
  workflow_dispatch:

jobs:
  generate-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install create-compose-app tool
      - name: Install create-compose-app
        run: sudo npm install -g create-compose-app

      # Step 3: Generate a new Compose app
      - name: Create Compose App
        run: create-compose-app --platform android --output ./compose-app

      # Step 4: Add Internet permission to AndroidManifest.xml
      - name: Add Internet Permission
        run: |
          echo '<uses-permission android:name="android.permission.INTERNET"/>' >> compose-app/app/src/main/AndroidManifest.xml

      # Step 5: Update MainActivity with basic setup
      - name: Update MainActivity
        run: |
          echo 'package com.example.composeapp

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material3.Text

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Text("Hello, Compose!")
        }
    }
}' > compose-app/app/src/main/java/com/example/composeapp/MainActivity.kt

      # Step 6: Build the project to validate setup
      - name: Build Android Project
        run: ./gradlew build
        working-directory: compose-app
