name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create project structure
        run: |
          mkdir -p app/src/main/java/com/example/app
          mkdir -p app/src/main/res/values

      - name: Create settings.gradle.kts
        run: |
          echo 'pluginManagement {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          dependencyResolutionManagement {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "ComposeApp"
          include(":app")' > settings.gradle.kts

      - name: Create build.gradle.kts
        run: |
          echo 'plugins {
              id("com.android.application") version "8.1.0" apply false
              id("org.jetbrains.kotlin.android") version "1.8.10" apply false
          }' > build.gradle.kts

      - name: Create app/build.gradle.kts
        run: |
          echo 'plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
          }
          
          android {
              namespace = "com.example.app"
              compileSdk = 33
              
              defaultConfig {
                  applicationId = "com.example.app"
                  minSdk = 24
                  targetSdk = 33
                  versionCode = 1
                  versionName = "1.0"
              }
              
              buildFeatures {
                  compose = true
              }
              
              composeOptions {
                  kotlinCompilerExtensionVersion = "1.4.0"
              }
              
              kotlinOptions {
                  jvmTarget = "1.8"
              }
          }
          
          dependencies {
              val composeBom = platform("androidx.compose:compose-bom:2023.01.00")
              implementation(composeBom)
              implementation("androidx.activity:activity-compose:1.6.1")
              implementation("androidx.compose.material3:material3")
              implementation("androidx.compose.ui:ui")
              implementation("androidx.compose.ui:ui-tooling-preview")
              debugImplementation("androidx.compose.ui:ui-tooling")
          }' > app/build.gradle.kts

      - name: Create gradle.properties
        run: |
          echo 'android.useAndroidX=true
          org.gradle.jvmargs=-Xmx2048m' > gradle.properties

      - name: Create AndroidManifest.xml
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application android:label="@string/app_name">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>' > app/src/main/AndroidManifest.xml

      - name: Create strings.xml
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">Compose App</string>
          </resources>' > app/src/main/res/values/strings.xml

      - name: Create MainActivity.kt
        run: |
          echo 'package com.example.app

          import android.os.Bundle
          import androidx.activity.ComponentActivity
          import androidx.activity.compose.setContent
          import androidx.compose.material3.Text
          import androidx.compose.runtime.Composable
          import androidx.compose.ui.tooling.preview.Preview

          class MainActivity : ComponentActivity() {
              override fun onCreate(savedInstanceState: Bundle?) {
                  super.onCreate(savedInstanceState)
                  setContent {
                      Greeting("Compose")
                  }
              }
          }

          @Composable
          fun Greeting(name: String) {
              Text(text = "Hello $name!")
          }

          @Preview
          @Composable
          fun PreviewGreeting() {
              Greeting("Preview")
          }' > app/src/main/java/com/example/app/MainActivity.kt

      - name: Initialize Gradle Wrapper
        run: gradle wrapper

      - name: Build with Gradle
        run: ./gradlew build

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Setup Kotlin Compose project"
          git push