name: Generate Android App Project

on:
  push:
    branches:
      - main

jobs:
  generate-android-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Create initial Gradle files
        run: |
          mkdir -p app/src/main
          echo "rootProject.name = \"minimal-shop\"" > settings.gradle.kts
          echo "plugins { application }" > build.gradle.kts

      - name: Initialize Gradle wrapper
        run: gradle wrapper

      - name: Generate Android project
        run: |
          ./gradlew init \
            --type android-application \
            --dsl kotlin \
            --project-name MyComposeApp \
            --package com.example.mycomposeapp \
            --language kotlin

      - name: Add internet permissions to AndroidManifest.xml
        run: |
          if [ -f "app/src/main/AndroidManifest.xml" ]; then
            sed -i '/<application/i\    <uses-permission android:name="android.permission.INTERNET" />' app/src/main/AndroidManifest.xml
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generated new Android project with internet permissions"
          git push
